[package]
name = "ca-authority"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = { version = "0.12.3", features = ["tls"] }
tokio = { version = "1.0", features = ["full"] }
boring = "4.0"
proto-schema = { path = "../proto-schema" }
rcgen = "0.13"
x509-parser = "0.16"
